name: Check README Links

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Links
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: README.md